// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservice.Context;

namespace ProductMicroservice.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20211218072613_2021_12_18_Initial")]
    partial class _2021_12_18_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductMicroservice.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Some example text.",
                            Image_Name = "1.jfif",
                            Name = "Iphone",
                            Price = 80000.0,
                            Rating = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Some example text.",
                            Image_Name = "1.jfif",
                            Name = "Bracelet",
                            Price = 2000.0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Some example text.",
                            Image_Name = "1.jfif",
                            Name = "Oneplus8",
                            Price = 40000.0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Some example text.",
                            Image_Name = "1.jfif",
                            Name = "Apple Watch",
                            Price = 15000.0,
                            Rating = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
